name: Test

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install pyMAISE
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential python3
    - name: Install libraries
      run: |
        pip3 install setuptools
        pip3 install pytest
        pip3 install -e .
    - name: Run tests
      run: |
        cd tests
        pytest .
